export const appTexts = {
    mainHeading: 'Welcome to the App',
    mainParagraph: 'This is a sample application demonstrating a universal stylesheet with light and dark themes using Styled Components in a React and TypeScript project.',
    toggleThemeButton: 'Toggle Theme',
    headerSectionTitle: 'Header',
    policiesSectionTitle: 'Your Policies',
    toolsSectionTitle: 'Tools & Support',
    coverageHeading: "You're fully covered.",
    coverageSubheading: 'You have 3 active policies with Vivre.',
    nextPaymentLabel: 'Next payment: $245.50 due Oct 25, 2025',
    makePaymentButton: 'Make a Payment',
    autoPolicyTitle: 'Auto Insurance',
    homePolicyTitle: 'Home Insurance',
    policyIdentifierAuto: 'Ford S-Max',
    policyIdentifierHome: '123 Meadow Lane',
    policyNumberPrefix: 'Policy No. ',
    viewDetailsButton: 'View Details',
    payNowButton: 'Pay Now',
    statusActive: 'Active',
    statusAtRisk: 'Payment Due',
    statusLapsed: 'Lapsed',
    toolFileClaim: 'File a Claim',
    toolRoadsideAssistance: 'Get Roadside Assistance',
    toolContactSupport: 'Contact Support',
    keyCoverageTitle: 'KEY COVERAGE',
    coverageBodilyInjury: 'Third-Party Liability',
    coveragePropertyDamage: 'Property Damage Liability',
    coverageCollision: 'Collision Coverage',
    premiumAmountPrefix: 'Premium:',
    nextPaymentDuePrefix: 'Next Payment:',
    panelTitleSuffix: ' Details',
    tabCoverage: 'Coverage Details',
    tabBilling: 'Billing & Documents',
    tabVehicle: 'Vehicle Information',
    downloadIdCardButton: 'Download ID Card',
    nextPaymentSectionTitle: 'Next Payment',
    paymentHistorySectionTitle: 'Payment History',
    documentsSectionTitle: 'Documents',
    paymentAmount: 'Amount',
    paymentDueDate: 'Due Date',
    paymentMethod: 'Payment Method',
};