export const appTexts = {
    mainHeading: 'Welcome to the App',
    mainParagraph: 'This is a sample application demonstrating a universal stylesheet with light and dark themes using Styled Components in a React and TypeScript project.',
    toggleThemeButton: 'Toggle Theme',
    headerSectionTitle: 'Header',
    policiesSectionTitle: 'Your Policies',
    toolsSectionTitle: 'Tools & Support',
    coverageHeading: "You're fully covered.",
    coverageSubheading: 'You have 3 active policies with Vivre.',
    nextPaymentLabel: 'Next payment: {currency}{amount} due {date}',
    makePaymentButton: 'Make a Payment',
    autoPolicyTitle: 'Auto Insurance',
    homePolicyTitle: 'Home Insurance',
    healthPolicyTitle: 'Health Insurance',
    petPolicyTitle: 'Pet Insurance',
    lifeUpsellTitle: 'Protect Their Future',
    lifeUpsellBody: "Secure your family's future with a Vivre Life Insurance policy. Get a personalized quote in minutes.",
    getQuoteButton: 'Get a Quote',
    policyIdentifierAuto: 'Ford S-Max',
    policyIdentifierHome: '10 Downing Street, London',
    policyIdentifierHealth: 'Kate Crestwell',
    policyIdentifierPet: 'Buddy (Golden Retriever)',
    policyNumberPrefix: 'Policy No. ',
    applicationNumberPrefix: 'Application No. ',
    viewDetailsButton: 'View Details',
    payNowButton: 'Pay Now',
    checkStatusButton: 'Check Status',
    statusActive: 'Active',
    statusAtRisk: 'Payment Due',
    statusLapsed: 'Lapsed',
    statusPending: 'Pending Review',
    toolFileClaim: 'File a Claim',
    toolRoadsideAssistance: 'Get Roadside Assistance',
    toolContactSupport: 'Contact Support',
    keyCoverageTitle: 'KEY COVERAGE',
    coverageBodilyInjury: 'Third-Party Liability',
    coveragePropertyDamage: 'Property Damage Liability',
    coverageCollision: 'Collision Coverage',
    premiumAmountPrefix: 'Premium:',
    nextPaymentDuePrefix: 'Next Payment:',
    panelTitleSuffix: ' Details',
    tabCoverage: 'Coverage Details',
    tabBilling: 'Billing & Docs',
    tabVehicle: 'Vehicle Info',
    tabProperty: 'Property Details',
    tabMember: 'Member Details',
    tabClaims: 'Claims',
    tabStatus: 'App Status',
    tabDocuments: 'Documents',
    downloadIdCardButton: 'Download Digital ID Card',
    uploadDocumentsButton: 'Upload More Documents',
    nextPaymentSectionTitle: 'Next Payment',
    paymentHistorySectionTitle: 'Payment History',
    documentsSectionTitle: 'Documents',
    paymentAmount: 'Amount',
    paymentDueDate: 'Due Date',
    paymentMethod: 'Payment Method',
};